name: dotnet build EXE and test

on: [push]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: ~/.nuget/packages
          # Look to see if there is a cache hit for the corresponding requirements file
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
          restore-keys: |
            ${{ runner.os }}-nuget
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '3.1.x'
      - name: Install dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --configuration Release --no-restore
      - name: Build single-file EXE
        run: dotnet publish LZXAuto --configuration Release
      - name: Push EXE online
        shell: pwsh
        run: |
          $publishFolder = Get-ChildItem -Path 'LZXAuto\bin\Release' -Recurse -Include 'publish'
          $file = Get-ChildItem -Path $publishFolder -Recurse -Include '*.exe'
          $zipFileName = "LZXAuto-$( Get-Date -Format 'yyyyMMddHHmm' ).zip"
          Get-FileHash -Algorithm SHA256 -Path $file
          Compress-Archive -LiteralPath $file.FullName -CompressionLevel 'Optimal' -DestinationPath $zipFileName
          $res = Invoke-RestMethod -uri 'https://paste.c-net.org/' -Method Put -InFile $zipFileName -ContentType 'multipart/form-data' -Headers @{ 'X-FileName' = $zipFileName ; 'x-random' = '' }
          Write-Host "Download $($zipFileName) from $($res.html.body.div.a.href)"
      - name: Test
        run: dotnet test --no-restore --verbosity normal
